curl -X POST http://127.0.0.1:5000/organizations \
-H "Content-Type: application/json" \
-d '{
    "name": "Nova Organização",
    "subject": {
        "username": "novo_usuario",
        "full_name": "Novo Usuário",
        "email": "usuario@example.com",
        "public_key": "chave_publica_exemplo"
    }
}'



curl -X GET http://127.0.0.1:5000/organizations



curl -X POST http://127.0.0.1:5000/sessions \
-H "Content-Type: application/json" \
-d '{
    "username": "novo_usuario",
    "organization_name": "Nova Organização",
    "identifier": "sessao_unica_id",
    "keys": {"chave": "valor"},
    "password": "senha_segura",
    "credentials": {"permissao": "admin"}
}'


curl -X POST -F "file=@./filetest.txt" http://localhost:5000/upload

curl -O http://localhost:5000/download/filetest.txt
