curl -X POST http://127.0.0.1:5000/organizations \
          -H "Content-Type: application/json" \
          -d '{
          "name": "deti",
          "subject": {
              "username": "deti",
              "full_name": "deti",
              "email": "deti@deti.com",
              "public_key": "detieky"
          }
      }'


curl -X GET http://127.0.0.1:5000/organizations



curl -X POST http://127.0.0.1:5000/sessions \
-H "Content-Type: application/json" \
-d '{
    "username": "deti",
    "organization_name": "deti",
    "identifier": "sessao_unica_deti",
    "keys": {"public_key": "detieky"},
    "password": "password",
    "credentials": {"permissao": "admin"}
}'


curl -X POST -F "file=@./filetest.txt" http://localhost:5000/upload

curl -O http://localhost:5000/download/filetest.txt
