curl -X POST http://127.0.0.1:5000/organizations \
          -H "Content-Type: application/json" \
          -d '{
          "name": "onu",
          "subject": {
              "username": "user",
              "full_name": "username",
              "email": "user@gmail.com",
              "public_key": "kei"
          }
      }'


curl -X GET http://127.0.0.1:5000/organizations



curl -X POST http://127.0.0.1:5000/sessions \
-H "Content-Type: application/json" \
-d '{
    "username": "user",
    "organization_name": "onu",
    "identifier": "onusession",
    "session_key": "key",
    "password": "password",
    "credentials": {"permissao": "admin"}
}'


curl -X POST -F "file=@./filetest.txt" http://localhost:5000/upload

curl -O http://localhost:5000/download/filetest.txt


