"""Adiciona os campos password e credentials ao modelo Session

Revision ID: 9308b18fc9c5
Revises: 
Create Date: 2024-11-01 10:35:40.297262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9308b18fc9c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('credentials', sa.JSON(), nullable=False))
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])
        batch_op.create_foreign_key(None, 'subject', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('credentials')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
