curl -X POST http://127.0.0.1:5000/organizations \
          -H "Content-Type: application/json" \
          -d '{
          "name": "onu",
          "subject": {
              "username": "user",
              "full_name": "username",
              "email": "user@gmail.com",
              "public_key": "key"
          }
      }'

curl -X POST http://127.0.0.1:5000/organizations \
-H "Content-Type: application/json" \
-d '{
    "name": "Org",
    "subject": {
        "username": "example_user",
        "full_name": "Example User",
        "email": "user@example.com",
        "public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoStw2U35hcfW5O6Ca29c\n7FwofsDTmJtkZMohyBdVH2fVIFiPG8RIhEJxXMk0j5PuoxK5JbzeH9GRsGJtNXOy\n6PHTMdf8zX4GsZZGYhd8onUwqHDfKYRdu8YkGxMZSQ2W2CowK2mhgv6cqU3OmZKP\nRhQjd4X8BhbAthS+Sq+iOJHgjCY60FsEp5/TrlhrF0p9QEPAkTgRFGxw/h0aVpIW\nN4L+tHnSxXM2SnxLRKN/9FJkoQdLt9+IH+l4QX6oFvJ9RdXHFylJ3g1uirY0seyA\n66qhP60EXbxbwkw6wTwYOOUtK8J4J8bVmazeOaZ2RXtufyqkajPukBZd1Zr3L9TV\nvQIDAQAB\n-----END PUBLIC KEY-----"
    }
}'


curl -X POST http://127.0.0.1:5000/organizations \
-H "Content-Type: application/json" \
-d '{
    "name": "Org2",
    "subject": {
        "username": "example_user2",
        "full_name": "Example User2",
        "email": "user2@example.com",
        "public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA66222Sk7r4umHirip14vp84\n/WhNYu9lLQl+P0v7ZXBdpyowEboJhi2K7oP85GKNG81ehk54GV3rz1lzP5MXdy8q\nMkmOBq5h49rusR+7MT7WGKUuqSiNOo5+Ed0qPuL7wCr8TBFOgbMvq2k6vcPava62\nnwJb125ADX6YhD5lA/HQKJBQIy8VrnCYBMT+AiiJ+trFVpvBQFhP3xlwuotRUVbw\nN8L/ClfSovj3wn8jeCGpz+e6WVo11OYI0o0FsyYzimmDvEA2c0ZGtqPnoBL0LyD1\nn3vTlfa0kAl2BIoVdVlDx2SQ3peDchvnuUJPbo+j2TuaI1qbb3qLV77PY12ECkoh\nPQIDAQAB\n-----END PUBLIC KEY-----"
    }
}'


curl -X GET http://127.0.0.1:5000/organizations

curl -X POST http://127.0.0.1:5000/organizations \
-H "Content-Type: application/json" \
-d '{
    "name": "Org",
    "subject": {
        "username": "example_user",
        "full_name": "Example User",
        "email": "user@example.com",
        "public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoStw2U35hcfW5O6Ca29c\n7FwofsDTmJtkZMohyBdVH2fVIFiPG8RIhEJxXMk0j5PuoxK5JbzeH9GRsGJtNXOy\n6PHTMdf8zX4GsZZGYhd8onUwqHDfKYRdu8YkGxMZSQ2W2CowK2mhgv6cqU3OmZKP\nRhQjd4X8BhbAthS+Sq+iOJHgjCY60FsEp5/TrlhrF0p9QEPAkTgRFGxw/h0aVpIW\nN4L+tHnSxXM2SnxLRKN/9FJkoQdLt9+IH+l4QX6oFvJ9RdXHFylJ3g1uirY0seyA\n66qhP60EXbxbwkw6wTwYOOUtK8J4J8bVmazeOaZ2RXtufyqkajPukBZd1Zr3L9TV\nvQIDAQAB\n-----END PUBLIC KEY-----"
    }
}'


curl -X POST http://127.0.0.1:5000/sessions \
-H "Content-Type: application/json" \
-d '{
    "username": "example_user",
    "organization_name": "Org",
    "identifier": "orgsession",
    "session_key": "key",
    "password": "password",
    "credentials": {"permissao": "admin"}
}'


curl -X POST http://localhost:5000/add_document \
              -F "session_key=key" \
              -F "document_name=windown" \
              -F "file=@./windown.jpg"

[
  {
    "document_id": 1, 
    "message": "Documento adicionado com sucesso"
  }, 
  201
]


curl -X GET "http://localhost:5000/document/metadata?document_name=test" \
     -H "session_key: key"

curl -X GET "http://localhost:5000/document/metadata?document_name=file" \
               -H "session_key: key"
[
  {
    "metadata": {
      "create_date": "Sat, 02 Nov 2024 15:35:54 GMT", 
      "creator": "user", 
      "document_handle": "animegurl", 
      "document_id": 1, 
      "document_name": "animegurl1.jpg", 
      "organization_id": 1
    }
  }, 
  200
]

curl -X GET http://localhost:5000/download_document/key/animegurl --output animegurl.jpg


curl -X POST http://localhost:5000/add_subject \
     -H "Content-Type: application/json" \
     -d '{
           "session_key": "your_session_key",
           "username": "your_username",
           "name": "subject_name",
           "email": "subject_email@example.com",
           "public_key": "your_public_key"
         }'


curl -O http://localhost:5000/download/filetest.txt


