"""session keys columns

Revision ID: 6b90d2412b45
Revises: 9308b18fc9c5
Create Date: 2024-11-02 10:34:25.146983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b90d2412b45'
down_revision = '9308b18fc9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_key', sa.JSON(), nullable=False))
        batch_op.drop_column('keys')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keys', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_column('session_key')

    # ### end Alembic commands ###
